language: objective-c 
compiler:
  - gcc
  - clang
branches:
  except:
    - gh-pages
before_install:
 - sudo brew update
 - sudo brew install nasm
install: make gtest-bootstrap
script: make && make test

