language: objective-c 
compiler:
  - clang
before_install:
 - brew update
 - brew install nasm
install: make gtest-bootstrap
script: make -B ENABLE64BIT=Yes && make test && make -B ENABLE64BIT=Yes BUILDTYPE=Release && make test && make -B && make test && make -B BUILDTYPE=Release && make test

