language: objective-c 
compiler:
  - gcc
  - clang
branches:
  except:
    - gh-pages
before_install:
 - brew update
 - brew install nasm
install: make gtest-bootstrap
script: make && make test && make clean && make ENABLE64BIT=Yes && make test

