language: objective-c 
compiler:
  - clang
branches:
  except:
    - gh-pages
before_install:
 - brew update
 - brew install nasm
install: make gtest-bootstrap
# libssl is not multiarch so we are building 64bit
# and then installing the 32bit version
script: make -B ENABLE64BIT=Yes && make test && make -B ENABLE64BIT=Yes BUILDTYPE=Release && make test && sudo apt-get install -qq libssl-dev:i386 && make -B && make test && make -B BUILDTYPE=Release && make test

